name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/bioconda/bioconda-recipes.git
          git fetch upstream

      - name: Rebase from upstream
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories

      - name: Push to fork
        run: |
          git push https://x-access-token:${{ secrets.BIOCONDA_SYNC_PAT }}@github.com/${{ github.repository }}.git HEAD:master --force
